PORTNAME= 	plano-theme
PORTVERSION=	4.0
DISTVERSIONPREFIX=v
CATEGORIES=		x11-themes

MAINTAINER=		totalslinux@gmail.com
COMMENT=	flat theme for GNOME & Xfce4

LICENSE= 	GPLv3

USES = 	meson

USE_GITHUB= YES
GH_ACCOUNT= lassekongo83

.include <bsd.port.mk>
