PORTNAME=      sway-input-config
PORTVERSION=   1.3.3
DISTVERSIONPREFIX= v
CATEGORIES=    x11 wayland

MAINTAINER=    totalslinux@gmail.com
COMMENT=      Sway input settings

LICENSE=      GPLv3

USE_GITHUB=   yes
GH_ACCOUNT=   Sunderland93

BUILD_DEPENDS=	wayland-protocols>0:graphics/wayland-protocols \



USES=		python
USE_PYTHON=	autoplist distutils unittest



.include <bsd.port.mk>
